version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: dmitrystepanov24/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: dmitrystepanov24/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: dmitrystepanov24/foodgram_gateway
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend