MAX_LENGTH_TAG = 32
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_INGREDIENT_MEASUREMENT_UNIT = 64
MAX_LENGTH_RECIPE_NAME = 256
RECIPE_INGREDIENT_AMOUNT = 1
MAX_TIME_COOKING = 32000

MAX_LENGTH_USERS = 150
