# Generated by Django 3.2 on 2024-07-11 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время в минутах', validators=[django.core.validators.MinValueValidator(1, message='минимально допустимое значение 1'), django.core.validators.MaxValueValidator(32000, message='максимально допустимое значение 32000')]),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='минимально допустимое значение 1'), django.core.validators.MaxValueValidator(32000, message='максимально допустимое значение 32000')]),
        ),
    ]
